doctrine:
    dbal:
        types:
            # Address
            point: App\Infrastructure\DBAL\Doctrine\Types\PointType

        default_connection: default
        connections:
            default:
                driver: pdo_pgsql
                url: '%env(resolve:DATABASE_URL)%'
                use_savepoints: true


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Core\Domain\Country:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Core/Domain/Country/Entity'
                prefix: 'App\Core\Domain\Country\Entity'
                alias: App
            App\Core\Domain\Region:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Core/Domain/Region/Entity'
                prefix: 'App\Core\Domain\Region\Entity'
                alias: App
            App\Core\Domain\City:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Core/Domain/City/Entity'
                prefix: 'App\Core\Domain\City\Entity'
                alias: App
            App\Core\Domain\Address:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Core/Domain/Address/Entity'
                prefix: 'App\Core\Domain\Address\Entity'
            App\Core\Domain\Currency:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Core/Domain/Currency/Entity'
                prefix: 'App\Core\Domain\Currency'
                alias: App
            App\Core\Domain\CurrencyRate:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Core/Domain/Currency/Entity'
                prefix: 'App\Core\Domain\CurrencyRate'
                alias: App
            App\Core\Domain\Language:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Core/Domain/Language/Entity'
                prefix: 'App\Core\Domain\Language'
                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@dev:
    doctrine:
        dbal:
            connections:
                default:
                    mapping_types:
                        point: point

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
